# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from internlm.param_server.proto import ps_pb2 as internlm_dot_param__server_dot_proto_dot_ps__pb2

GRPC_GENERATED_VERSION = '1.69.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in internlm/param_server/proto/ps_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ControlServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartUpdateWeight = channel.unary_unary(
                '/ps.ControlService/StartUpdateWeight',
                request_serializer=internlm_dot_param__server_dot_proto_dot_ps__pb2.StartUpdateWeightRequest.SerializeToString,
                response_deserializer=internlm_dot_param__server_dot_proto_dot_ps__pb2.StartUpdateWeightResponse.FromString,
                _registered_method=True)
        self.UpdateGroupList = channel.unary_unary(
                '/ps.ControlService/UpdateGroupList',
                request_serializer=internlm_dot_param__server_dot_proto_dot_ps__pb2.UpdateGroupListRequest.SerializeToString,
                response_deserializer=internlm_dot_param__server_dot_proto_dot_ps__pb2.UpdateGroupListResponse.FromString,
                _registered_method=True)
        self.FinishPullWeight = channel.unary_unary(
                '/ps.ControlService/FinishPullWeight',
                request_serializer=internlm_dot_param__server_dot_proto_dot_ps__pb2.FinishPullWeightRequest.SerializeToString,
                response_deserializer=internlm_dot_param__server_dot_proto_dot_ps__pb2.FinishPullWeightResponse.FromString,
                _registered_method=True)
        self.StartComputeNorm = channel.unary_unary(
                '/ps.ControlService/StartComputeNorm',
                request_serializer=internlm_dot_param__server_dot_proto_dot_ps__pb2.StartComputeNormRequest.SerializeToString,
                response_deserializer=internlm_dot_param__server_dot_proto_dot_ps__pb2.StartComputeNormResponse.FromString,
                _registered_method=True)


class ControlServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StartUpdateWeight(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateGroupList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FinishPullWeight(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartComputeNorm(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ControlServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartUpdateWeight': grpc.unary_unary_rpc_method_handler(
                    servicer.StartUpdateWeight,
                    request_deserializer=internlm_dot_param__server_dot_proto_dot_ps__pb2.StartUpdateWeightRequest.FromString,
                    response_serializer=internlm_dot_param__server_dot_proto_dot_ps__pb2.StartUpdateWeightResponse.SerializeToString,
            ),
            'UpdateGroupList': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateGroupList,
                    request_deserializer=internlm_dot_param__server_dot_proto_dot_ps__pb2.UpdateGroupListRequest.FromString,
                    response_serializer=internlm_dot_param__server_dot_proto_dot_ps__pb2.UpdateGroupListResponse.SerializeToString,
            ),
            'FinishPullWeight': grpc.unary_unary_rpc_method_handler(
                    servicer.FinishPullWeight,
                    request_deserializer=internlm_dot_param__server_dot_proto_dot_ps__pb2.FinishPullWeightRequest.FromString,
                    response_serializer=internlm_dot_param__server_dot_proto_dot_ps__pb2.FinishPullWeightResponse.SerializeToString,
            ),
            'StartComputeNorm': grpc.unary_unary_rpc_method_handler(
                    servicer.StartComputeNorm,
                    request_deserializer=internlm_dot_param__server_dot_proto_dot_ps__pb2.StartComputeNormRequest.FromString,
                    response_serializer=internlm_dot_param__server_dot_proto_dot_ps__pb2.StartComputeNormResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ps.ControlService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ps.ControlService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ControlService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartUpdateWeight(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ps.ControlService/StartUpdateWeight',
            internlm_dot_param__server_dot_proto_dot_ps__pb2.StartUpdateWeightRequest.SerializeToString,
            internlm_dot_param__server_dot_proto_dot_ps__pb2.StartUpdateWeightResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateGroupList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ps.ControlService/UpdateGroupList',
            internlm_dot_param__server_dot_proto_dot_ps__pb2.UpdateGroupListRequest.SerializeToString,
            internlm_dot_param__server_dot_proto_dot_ps__pb2.UpdateGroupListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FinishPullWeight(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ps.ControlService/FinishPullWeight',
            internlm_dot_param__server_dot_proto_dot_ps__pb2.FinishPullWeightRequest.SerializeToString,
            internlm_dot_param__server_dot_proto_dot_ps__pb2.FinishPullWeightResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartComputeNorm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ps.ControlService/StartComputeNorm',
            internlm_dot_param__server_dot_proto_dot_ps__pb2.StartComputeNormRequest.SerializeToString,
            internlm_dot_param__server_dot_proto_dot_ps__pb2.StartComputeNormResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
