# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: internlm/param_server/proto/ps.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'internlm/param_server/proto/ps.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$internlm/param_server/proto/ps.proto\x12\x02ps\"3\n\x11GroupWeightFactor\x12\x10\n\x08group_id\x18\x01 \x01(\x05\x12\x0c\n\x04norm\x18\x02 \x01(\x02\"\xa1\x01\n\x18StartUpdateWeightRequest\x12\x0e\n\x06groups\x18\x01 \x03(\x05\x12&\n\x07\x66\x61\x63tors\x18\x02 \x03(\x0b\x32\x15.ps.GroupWeightFactor\x12\x0f\n\x07version\x18\x03 \x01(\x05\x12\x16\n\x0e\x63onsume_tokens\x18\x04 \x01(\x03\x12\x11\n\tsave_ckpt\x18\x05 \x01(\x08\x12\x11\n\tclip_coef\x18\x06 \x01(\x02\"\x1b\n\x19StartUpdateWeightResponse\"(\n\x16UpdateGroupListRequest\x12\x0e\n\x06groups\x18\x01 \x03(\x05\"\x19\n\x17UpdateGroupListResponse\")\n\x17StartComputeNormRequest\x12\x0e\n\x06groups\x18\x01 \x03(\x05\"\x1a\n\x18StartComputeNormResponse\"\x19\n\x17\x46inishPullWeightRequest\"\x1a\n\x18\x46inishPullWeightResponse2\xcc\x02\n\x0e\x43ontrolService\x12P\n\x11StartUpdateWeight\x12\x1c.ps.StartUpdateWeightRequest\x1a\x1d.ps.StartUpdateWeightResponse\x12J\n\x0fUpdateGroupList\x12\x1a.ps.UpdateGroupListRequest\x1a\x1b.ps.UpdateGroupListResponse\x12M\n\x10\x46inishPullWeight\x12\x1b.ps.FinishPullWeightRequest\x1a\x1c.ps.FinishPullWeightResponse\x12M\n\x10StartComputeNorm\x12\x1b.ps.StartComputeNormRequest\x1a\x1c.ps.StartComputeNormResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'internlm.param_server.proto.ps_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GROUPWEIGHTFACTOR']._serialized_start=44
  _globals['_GROUPWEIGHTFACTOR']._serialized_end=95
  _globals['_STARTUPDATEWEIGHTREQUEST']._serialized_start=98
  _globals['_STARTUPDATEWEIGHTREQUEST']._serialized_end=259
  _globals['_STARTUPDATEWEIGHTRESPONSE']._serialized_start=261
  _globals['_STARTUPDATEWEIGHTRESPONSE']._serialized_end=288
  _globals['_UPDATEGROUPLISTREQUEST']._serialized_start=290
  _globals['_UPDATEGROUPLISTREQUEST']._serialized_end=330
  _globals['_UPDATEGROUPLISTRESPONSE']._serialized_start=332
  _globals['_UPDATEGROUPLISTRESPONSE']._serialized_end=357
  _globals['_STARTCOMPUTENORMREQUEST']._serialized_start=359
  _globals['_STARTCOMPUTENORMREQUEST']._serialized_end=400
  _globals['_STARTCOMPUTENORMRESPONSE']._serialized_start=402
  _globals['_STARTCOMPUTENORMRESPONSE']._serialized_end=428
  _globals['_FINISHPULLWEIGHTREQUEST']._serialized_start=430
  _globals['_FINISHPULLWEIGHTREQUEST']._serialized_end=455
  _globals['_FINISHPULLWEIGHTRESPONSE']._serialized_start=457
  _globals['_FINISHPULLWEIGHTRESPONSE']._serialized_end=483
  _globals['_CONTROLSERVICE']._serialized_start=486
  _globals['_CONTROLSERVICE']._serialized_end=818
# @@protoc_insertion_point(module_scope)
